---
# PROD VRF
PROD:
  - name: PROD_TENANT
    mac_vrf_vni_base: 10000
    vrfs:
      - name: PROD
        vrf_vni: 50001
        mlag_ibgp_peering_vlan: 3001
        vtep_diagnostic:
          loopback: 101
          loopback_ip_pools:
            - pod: SITEA_POD
              ipv4_pool: 10.101.101.0/24
        svis:
          - id: 10
            name: PROD_10
            enabled: true
            ip_address_virtual: 10.10.10.1/24
          - id: 30
            name: PROD_30
            enabled: true
            ip_address_virtual: 10.30.30.1/24
