---
# IP transport fabric
fabric_name: IP_TRANSPORT

# IP transport nodes
type: overlay-controller

overlay_controller:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65000
    loopback_ipv4_pool: 172.16.0.0/26
    structured_config:
        router_bgp:
          peer_groups:
            - name: IP-TRANSPORT-CLIENTS
              bfd: true
          address_family_ipv4:
            peer_groups:
              - name: IP-TRANSPORT-CLIENTS
                activate: true
  nodes:
    - name: BB1
      id: 1
      mgmt_ip: 172.100.100.138/24
      structured_config:
        router_bgp:
          address_family_ipv4:
            networks:
              - prefix: 172.16.0.1/32

    - name: BB2
      id: 2
      mgmt_ip: 172.100.100.126/24
      structured_config:
        router_bgp:
          address_family_ipv4:
            networks:
              - prefix: 172.16.0.2/32

# BGP custom variables
bgp_peer_groups:
  evpn_overlay_peers:
    structured_config:
      ebgp_multihop: 5

custom_structured_configuration_router_bgp:
  listen_ranges:
    - prefix: 10.0.0.0/24
      peer_group: EVPN-OVERLAY-PEERS
      peer_filter: DC-ASN-RANGE
    - prefix: 172.16.0.0/16
      peer_group: IP-TRANSPORT-CLIENTS
      peer_filter: DC-ASN-RANGE

custom_structured_configuration_peer_filters:
  - name: DC-ASN-RANGE
    sequence_numbers:
      - sequence: 10
        match: "as-range 65100-65499 result accept"

