---
# IP transport fabric
fabric_name: IP_TRANSPORT

# IP transport nodes
type: overlay-controller

overlay_controller:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65000
    loopback_ipv4_pool: 172.16.0.0/26
  nodes:
    - name: BB1
      id: 1
      mgmt_ip: 172.100.100.138/24
    - name: BB2
      id: 2
      mgmt_ip: 172.100.100.126/24

# BGP custom variables
bgp_peer_groups:
  evpn_overlay_peers:
    structured_config:
      ebgp_multihop: 5

custom_structured_configuration_router_bgp:
  listen_ranges:
    - prefix: 10.0.0.0/24
      peer_group: EVPN-OVERLAY-PEERS
      remote_as: 65000
