---

- name: Deploy hosts config for all sites
  hosts: host_nodes
  connection: local
  gather_facts: false
  vars:
    ansible_user: cvpadmin
    ansible_password: arista123
    ansible_network_os: arista.eos.eos
    # Configure privilege escalation
    ansible_become: true
    ansible_become_method: enable
    # HTTPAPI configuration
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_python_interpreter: $(which python3)
    ansible_httpapi_ciphers: AES256-SHA:DHE-RSA-AES256-SHA:AES128-SHA:DHE-RSA-AES128-SHA


  tasks:

    - name: Deploy configuration to all hosts
      arista.eos.eos_config:
        src: "{{ inventory_dir }}/intended/hosts_configs/{{ inventory_hostname }}.cfg"
        replace: config
        save_when: modified
