- name: validate states on EOS devices
  hosts: "{{target_hosts}}"
  connection: httpapi
  gather_facts: false
  collections:
    - arista.avd
  vars:
    ansible_user: 'cvpadmin'
    ansible_password: 'arista123'
    ansible_network_os: eos
    ansible_become: yes
    ansible_become_method: enable
    validation_mode_loose: true
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    # Use default EOS ciphers:
    ansible_httpapi_ciphers: AES256-SHA:DHE-RSA-AES256-SHA:AES128-SHA:DHE-RSA-AES128-SHA
    # Enable ANTA
    #use_anta: true

  tasks:
    - name: validate states on EOS devices
      import_role:
         name: arista.avd.eos_validate_state