---
type: spine

spine:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65300
    loopback_ipv4_pool: 10.0.0.0/24
    loopback_ipv4_offset: 130
  nodes:
    - name: C-SPINE1
      id: 1
      mgmt_ip: 172.100.100.127/24
    - name: C-SPINE2
      id: 2
      mgmt_ip: 172.100.100.128/24

custom_structured_configuration_router_bgp:
  listen_ranges:
    - prefix: 10.0.0.0/24
      peer_group: EVPN-OVERLAY-PEERS
      peer_filter: LEAF-AS-RANGE

custom_structured_configuration_peer_filters:
  - name: LEAF-AS-RANGE
    sequence_numbers:
      - sequence: 10
        match: "as-range 65301-65399 result accept"