---
type: l2leaf

l2leaf:
  defaults:
    platform: vEOS-LAB
    uplink_interfaces:
      - Ethernet1
      - Ethernet2
    uplink_switches:
      - B-LEAF1
      - B-LEAF2
  nodes:
    - name: B-SW1
      id: 1
      mgmt_ip: 172.100.100.139/24
      uplink_switch_interfaces:
        - Ethernet7
        - Ethernet7
      filter:
        tags: [ purple, black ]
