---
type: l2leaf

l2leaf:
  defaults:
    platform: vEOS-LAB
  nodes:
    - name: B-SW1
      id: 1
      mgmt_ip: 172.100.100.139/24
      filter:
        tags: [ purple, black ]
      structured_config:
        ethernet_interfaces:
          - name: Ethernet1
            description: B-LEAF5
            mode: trunk
          - name: Ethernet2
            description: B-LEAF6
            mode: trunk
