---
type: l3leaf

l3leaf:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65200
    loopback_ipv4_pool: 10.0.0.0/24
    loopback_ipv4_offset: 20
    vtep_loopback_ipv4_pool: 10.2.2.0/24
    uplink_interfaces:
      - Ethernet1
      - Ethernet2
      - Ethernet3
      - Ethernet4
    uplink_switches:
      - B-SPINE1
      - B-SPINE2
      - B-SPINE3
      - B-SPINE4
    mlag: false
    virtual_router_mac_address: 00:1c:73:00:00:01
    isis_system_id_prefix: '0000.0001'
    isis_maximum_paths: 4
    uplink_structured_config:
      ip_address: 'unnumbered loopback0'
      ipv6_enable: false
    link_tracking:
      enabled: true
      groups:
        - name: ES-LINKS
          recovery_delay: 300
    structured_config:
      router_bgp:
        address_family_evpn:
          route:
            import_match_failure_action: discard
  node_groups:
    - group: B-LEAF12
      filter:
        tags: [ green, purple ]
      nodes:
        - name: B-LEAF1
          id: 1
          mgmt_ip: 172.100.100.118/24
          uplink_switch_interfaces:
            - Ethernet1
            - Ethernet1
            - Ethernet1
            - Ethernet1
        - name: B-LEAF2
          id: 2
          mgmt_ip: 172.100.100.119/24
          uplink_switch_interfaces:
            - Ethernet2
            - Ethernet2
            - Ethernet2
            - Ethernet2
    - group: B-LEAF34
      filter:
        tags: [ blue, red, brown ]
      nodes:
        - name: B-LEAF3
          id: 3
          mgmt_ip: 172.100.100.120/24
          uplink_switch_interfaces:
            - Ethernet3
            - Ethernet3
            - Ethernet3
            - Ethernet3
        - name: B-LEAF4
          id: 4
          mgmt_ip: 172.100.100.121/24
          uplink_switch_interfaces:
            - Ethernet4
            - Ethernet4
            - Ethernet4
            - Ethernet4
    - group: B-LEAF56
      filter:
        tags: [ purple, black ]
      structured_config:
        port_channel_interfaces:
          - name: Port-Channel7
            evpn_ethernet_segment:
              identifier: 0000:0000:0025:0026:0007
              route_target: 00:25:00:26:00:07
            lacp_id: 0025.0026.0007
      nodes:
        - name: B-LEAF5
          id: 5
          mgmt_ip: 172.100.100.122/24
          uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
            - Ethernet5
            - Ethernet5
        - name: B-LEAF6
          id: 6
          mgmt_ip: 172.100.100.123/24
          uplink_switch_interfaces:
            - Ethernet6
            - Ethernet6
            - Ethernet6
            - Ethernet6
    - group: B-LEAF78
      filter:
        tags: [ blue, green, red, brown ]
      evpn_gateway:
        remote_peers:
          - hostname: BB1
            ip_address: 172.16.0.1
            bgp_as: 65000
          - hostname: BB2
            ip_address: 172.16.0.2
            bgp_as: 65000
        evpn_l2:
          enabled: true
        evpn_l3:
          enabled: true
      structured_config:
        router_bgp:
          peer_groups:
            - name: REMOTE-IPV4-PEERS
              remote_as: 65000
              bfd: true
          address_family_ipv4:
            peer_groups:
              - name: REMOTE-IPV4-PEERS
                activate: true
      nodes:
        - name: B-LEAF7
          id: 7
          mgmt_ip: 172.100.100.124/24
          uplink_switch_interfaces:
            - Ethernet7
            - Ethernet7
            - Ethernet7
            - Ethernet7
          structured_config:
            router_bgp:
              neighbors:
                - ip_address: 172.16.2.0
                  peer_group: REMOTE-IPV4-PEERS
                - ip_address: 172.16.2.4
                  peer_group: REMOTE-IPV4-PEERS
              address_family_ipv4:
                networks:
                  - prefix: 10.0.0.27/32
                  - prefix: 10.0.0.28/32
                  - prefix: 10.2.2.27/32
        - name: B-LEAF8
          id: 8
          mgmt_ip: 172.100.100.125/24
          uplink_switch_interfaces:
            - Ethernet8
            - Ethernet8
            - Ethernet8
            - Ethernet8
          structured_config:
            router_bgp:
              neighbors:
                - ip_address: 172.16.2.2
                  peer_group: REMOTE-IPV4-PEERS
                - ip_address: 172.16.2.6
                  peer_group: REMOTE-IPV4-PEERS
              address_family_ipv4:
                networks:
                  - prefix: 10.0.0.27/32
                  - prefix: 10.0.0.28/32
                  - prefix: 10.2.2.28/32
