---
# Endpoint connectivity
# Using network ports model
network_ports:
  - description: HostG
    switches:
      - B-LEAF1
      - B-LEAF2
    switch_ports:
      - Ethernet7
      - Ethernet7
    mode: access
    vlans: 20
    spanning_tree_portfast: edge
    ethernet_segment:
      short_esi: 0021:0022:0007
    port_channel:
      mode: active
      enabled: true
    link_tracking:
      enabled: true
      name: ES-LINKS
  - description: HostH
    switches:
      - B-LEAF1
      - B-LEAF2
    switch_ports:
      - Ethernet8
      - Ethernet8
    mode: access
    vlans: 40
    spanning_tree_portfast: edge
    ethernet_segment:
      short_esi: 0021:0022:0008
    port_channel:
      mode: active
      enabled: true
    link_tracking:
      enabled: true
      name: ES-LINKS
