---
# PROD VRF
PROD:
  - name: PROD_TENANT
    mac_vrf_vni_base: 10000
    # evpn_l3_multicast:
    #   enabled: true
    #   evpn_underlay_l3_multicast_group_ipv4_pool: 232.1.0.0/16
    vrfs:
      - name: PROD
        vrf_vni: 50001
        mlag_ibgp_peering_vlan: 3001
        vtep_diagnostic:
          loopback: 101
          loopback_ip_pools:
            - pod: SITEA_POD
              ipv4_pool: 10.101.101.0/24
        svis:
          - id: 10
            name: Blue
            tags: [blue]
            enabled: true
            ip_address_virtual: 10.10.10.1/24
          - id: 20
            name: Green
            tags: [green]
            enabled: true
            ip_address_virtual: 10.20.20.1/24
          - id: 30
            name: Orange
            tags: [orange]
            enabled: true
            ip_address_virtual: 10.30.30.1/24
          - id: 40
            name: Purple
            tags: [purple]
            enabled: true
            ip_address_virtual: 10.40.40.1/24
